# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Andrew/Developer/AutoMUSic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Andrew/Developer/AutoMUSic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Andrew/Developer/AutoMUSic/CMakeFiles /Users/Andrew/Developer/AutoMUSic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Andrew/Developer/AutoMUSic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named audio_io

# Build rule for target.
audio_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audio_io
.PHONY : audio_io

# fast build rule for target.
audio_io/fast:
	$(MAKE) -f CMakeFiles/audio_io.dir/build.make CMakeFiles/audio_io.dir/build
.PHONY : audio_io/fast

src/impl/AMUS_audio_io.o: src/impl/AMUS_audio_io.cpp.o
.PHONY : src/impl/AMUS_audio_io.o

# target to build an object file
src/impl/AMUS_audio_io.cpp.o:
	$(MAKE) -f CMakeFiles/audio_io.dir/build.make CMakeFiles/audio_io.dir/src/impl/AMUS_audio_io.cpp.o
.PHONY : src/impl/AMUS_audio_io.cpp.o

src/impl/AMUS_audio_io.i: src/impl/AMUS_audio_io.cpp.i
.PHONY : src/impl/AMUS_audio_io.i

# target to preprocess a source file
src/impl/AMUS_audio_io.cpp.i:
	$(MAKE) -f CMakeFiles/audio_io.dir/build.make CMakeFiles/audio_io.dir/src/impl/AMUS_audio_io.cpp.i
.PHONY : src/impl/AMUS_audio_io.cpp.i

src/impl/AMUS_audio_io.s: src/impl/AMUS_audio_io.cpp.s
.PHONY : src/impl/AMUS_audio_io.s

# target to generate assembly for a file
src/impl/AMUS_audio_io.cpp.s:
	$(MAKE) -f CMakeFiles/audio_io.dir/build.make CMakeFiles/audio_io.dir/src/impl/AMUS_audio_io.cpp.s
.PHONY : src/impl/AMUS_audio_io.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... audio_io"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/impl/AMUS_audio_io.o"
	@echo "... src/impl/AMUS_audio_io.i"
	@echo "... src/impl/AMUS_audio_io.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

